# Extract the data to load into Vespa
extract-documents:
    aws s3 cp s3://cpr-cache/search/vespa/documents_feed_materializer.jsonl ../.data_cache/vespa/documents_feed_materializer.jsonl

feed-documents:
    vespa feed ../.data_cache/vespa/documents_feed_materializer.jsonl --target http://localhost:8080 --progress 30

extract-documents-concepts:
    aws s3 cp s3://cpr-cache/search/vespa/documents_concepts_feed_materializer.jsonl ../.data_cache/vespa/documents_concepts_feed_materializer.jsonl

feed-documents-concepts:
    vespa feed ../.data_cache/vespa/documents_concepts_feed_materializer.jsonl --target http://localhost:8080 --progress 30

extract-labels:
    aws s3 cp s3://cpr-cache/search/vespa/labels_feed_materializer.jsonl ../.data_cache/vespa/labels_feed_materializer.jsonl

feed-labels:
    vespa feed ../.data_cache/vespa/labels_feed_materializer.jsonl --target http://localhost:8080 --progress 30

extract-passages:
    aws s3 cp s3://cpr-cache/search/vespa/passages_feed_materializer.jsonl.gz ../.data_cache/vespa/passages_feed_materializer.jsonl.gz
    gunzip -f ../.data_cache/vespa/passages_feed_materializer.jsonl.gz

feed-passages:
    vespa feed ../.data_cache/vespa/passages_feed_materializer.jsonl --target http://localhost:8080 --progress 30

# Run vespa dev
up:
    docker compose up -d

# Deploy Vespa application
deploy:
    vespa deploy ./app --target http://localhost:19071/ --wait 300

# Dev
dev:
    just up
    just deploy
    just feed 100

get query="congo":
    #!/usr/bin/env bash
    set -e
    curl -G "http://localhost:8080/search/" \
     --data-urlencode 'yql=select * from sources documents where userQuery()' \
     --data-urlencode 'query={{query}}' \
     --data-urlencode 'hits=10'

get-document id="CCLW.collection.1755.0":
    vespa document get "id:documents:documents::{{id}}"

# Remove the application. To remove data as well, use `reset` below.
destroy:
    curl -X DELETE http://localhost:19071/application/v2/tenant/default/application/default

# Remove the Vespa container and volume
reset:
    docker compose down -v

# remote command
remote-deploy:
    #!/usr/bin/env bash
    set -e
    # read this parameter from aws smm and store it in a variable it's a secret
    vespa_endpoint=$(aws ssm get-parameter --name "/search/vespa/endpoint" --query "Parameter.Value" --output text --with-decryption)
    vespa_application=$(aws ssm get-parameter --name "/search/vespa/application" --query "Parameter.Value" --output text --with-decryption)
    vespa prod deploy ./app --target cloud --application $vespa_application --zone prod.aws-eu-west-1a

remote-feed-documents:
    #!/usr/bin/env bash
    set -e
    vespa_write_token=$(aws ssm get-parameter --name "/search/vespa/write_token" --query "Parameter.Value" --output text --with-decryption)
    vespa_endpoint=$(aws ssm get-parameter --name "/search/vespa/endpoint" --query "Parameter.Value" --output text --with-decryption)
    vespa feed ../.data_cache/vespa/documents_feed_materializer.jsonl --target $vespa_endpoint --header "Authorization: Bearer $vespa_write_token" --progress 30

remote-feed-documents-concepts:
    #!/usr/bin/env bash
    set -e
    vespa_write_token=$(aws ssm get-parameter --name "/search/vespa/write_token" --query "Parameter.Value" --output text --with-decryption)
    vespa_endpoint=$(aws ssm get-parameter --name "/search/vespa/endpoint" --query "Parameter.Value" --output text --with-decryption)
    vespa feed ../.data_cache/vespa/documents_concepts_feed_materializer.jsonl --target $vespa_endpoint --header "Authorization: Bearer $vespa_write_token" --progress 30

remote-feed-labels:
    #!/usr/bin/env bash
    set -e
    vespa_write_token=$(aws ssm get-parameter --name "/search/vespa/write_token" --query "Parameter.Value" --output text --with-decryption)
    vespa_endpoint=$(aws ssm get-parameter --name "/search/vespa/endpoint" --query "Parameter.Value" --output text --with-decryption)
    vespa feed ../.data_cache/vespa/labels_feed_materializer.jsonl --target $vespa_endpoint --header "Authorization: Bearer $vespa_write_token" --progress 30

remote-feed-passages:
    #!/usr/bin/env bash
    set -e
    vespa_write_token=$(aws ssm get-parameter --name "/search/vespa/write_token" --query "Parameter.Value" --output text --with-decryption)
    vespa_endpoint=$(aws ssm get-parameter --name "/search/vespa/endpoint" --query "Parameter.Value" --output text --with-decryption)
    vespa feed ../.data_cache/vespa/passages_feed_materializer.jsonl --target $vespa_endpoint --header "Authorization: Bearer $vespa_write_token" --progress 30

remote-visit:
    #!/usr/bin/env bash
    set -e
    vespa_read_token=$(aws ssm get-parameter --name "/search/vespa/read_token" --query "Parameter.Value" --output text --with-decryption)
    vespa_endpoint=$(aws ssm get-parameter --name "/search/vespa/endpoint" --query "Parameter.Value" --output text --with-decryption)
    mkdir -p ../.data_cache/vespa
    vespa visit --target "$vespa_endpoint" --header "Authorization: Bearer $vespa_read_token" > "../.data_cache/vespa/documents-cloud.jsonl"
    echo "Exported to ../.data_cache/vespa/documents-cloud.jsonl"
