{
 "title": "Vespa: Search Instance",
 "tags": [
  "vespa",
  "search",
  "cloudwatch"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" }
  ]
 },
 "panels": [
  {
   "title": "Documents",
   "type": "timeseries",
   "description": "Total documents in the search Vespa instance.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production",
      "documenttype": "documents"
     },
     "metricName": "content.proton.documentdb.documents.total.last",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Passages",
   "type": "timeseries",
   "description": "Total passages in the search Vespa instance.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production",
      "documenttype": "passages"
     },
     "metricName": "content.proton.documentdb.documents.total.last",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Labels",
   "type": "timeseries",
   "description": "Total labels in the search Vespa instance.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production",
      "documenttype": "labels"
     },
     "metricName": "content.proton.documentdb.documents.total.last",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "Instance query rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "queries.rate",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Feed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "content.proton.documentdb.feeding.commit.operations.rate",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "95p (AVG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "query_latency.95percentile",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "99p (AVG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "query_latency.99percentile",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Mean Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "query_latency.average",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HTTP 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "http.status.2xx",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "http.status.4xx",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "http.status.5xx",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "cpu",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    },
    { "expression": "$A * 100", "type": "math" }
   ]
  },
  {
   "title": "Proton Document Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "content.proton.documentdb.disk_usage.last",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Proton Resource Disk Usage Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "content.proton.resource_usage.disk.average",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    },
    { "expression": "$A * 100", "type": "math" }
   ]
  },
  {
   "title": "Proton Memory Usage Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "applicationId": "climate-policy-radar.search.search-production"
     },
     "metricName": "content.proton.resource_usage.memory.average",
     "namespace": "vespa",
     "queryMode": "Metrics",
     "region": "eu-west-1",
     "statistic": "Average"
    },
    { "expression": "$A * 100", "type": "math" }
   ]
  }
 ]
}