gen-env instance="":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ -n "{{ instance }}" ]; then
        vespa_read_token=$(aws ssm get-parameter --name "/search/vespa-dev/read_token" --query "Parameter.Value" --output text --with-decryption)
        vespa_endpoint=$(aws ssm get-parameter --name "/search/vespa-dev/{{ instance }}" --query "Parameter.Value" --output text --with-decryption)
    else
        vespa_read_token=$(aws ssm get-parameter --name "/search/vespa/read_token" --query "Parameter.Value" --output text --with-decryption)
        vespa_endpoint=$(aws ssm get-parameter --name "/search/vespa/endpoint" --query "Parameter.Value" --output text --with-decryption)
    fi
    touch ./.env
    echo "VESPA_READ_TOKEN=$vespa_read_token" > ./.env
    echo "VESPA_ENDPOINT=$vespa_endpoint" >> ./.env

dev:
    uv run fastapi dev ./main.py --port 8000
