name: Merge to Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

# There is a lot of services deployed in this workflow, so this avoids
# deploying over each other by using concurrent runs (cancel-in-progress: false)
# We could use merge queues, but that is a little more inferred than explicit
concurrency:
  group: merge-to-main
  cancel-in-progress: false

permissions:
  contents: write
  # needed for reading the OIDC token and assuming the role
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      run-test: ${{ steps.filter.outputs.run-test }}
      run-pulumi-up: ${{ steps.filter.outputs.run-pulumi-up }}
      run-deploy: ${{ steps.filter.outputs.run-deploy }}
      run-vespa-deploy: ${{ steps.filter.outputs.run-vespa-deploy }}
      run-prefect-deploy: ${{ steps.filter.outputs.run-prefect-deploy }}
      run-vespa-feeder-deploy: ${{ steps.filter.outputs.run-vespa-feeder-deploy }}
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            run-test:
              - 'api/**'
              - 'relevance_tests/**'
              - 'search/**'
              - 'tests/**'
              - 'vespa/**'
              - 'uv.lock'
              - pyproject.toml
            run-pulumi-up:
              - 'infra/**'
            run-deploy:
              - 'api/**'
              - 'search/**'
            run-vespa-deploy:
              - 'vespa/app/**'
            run-prefect-deploy:
              - 'deployments.py'
              - 'prefect/**'
              - 'pyproject.toml'
              - 'uv.lock'
              - 'online_metrics/**'
              - 'relevance_tests/**'
              - 'search/vespa/**'
            run-vespa-feeder-deploy:
              - 'vespa-feeder/**'

  lint:
    permissions:
      # For trunk to post annotations
      checks: write
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install just
        uses: extractions/setup-just@v4
      - name: Install python or load from cache with dependencies
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: just install
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          arguments: --ci

  test:
    runs-on: ubuntu-latest
    needs: [changes]
    steps:
      # The conditional is on this composite action, so that the step always runs, and can be `needed` by subsequent jobs.
      # If the job was conditional, it would be `skipped`, and thus subsequent steps, and any steps in its closure would be considered skipped top.
      # @see: https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-jobs#:~:text=If%20a%20run%20contains%20a%20series%20of%20jobs%20that%20need%20each%20other%2C%20a%20failure%20or%20skip%20applies%20to%20all%20jobs%20in%20the%20dependency%20chain%20from%20the%20point%20of%20failure%20or%20skip%20onwards
      # @see: https://github.com/climatepolicyradar/search/pull/356
      # We use a composite action to avoid needing to run the conditional on each step in this job, which would be verbose and error-prone.
      - uses: actions/checkout@v7
      - if: needs.changes.outputs.run-test == 'true'
        uses: ./.github/actions/test

  deploy-api-apprunner-deprecated:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    needs: [changes, test]
    if: needs.changes.outputs.run-deploy == 'true'

  # @see: https://github.com/marketplace/actions/amazon-ecs-deploy-express-service-action-for-github-actions#complete-example-with-all-options
  deploy-api:
    uses: ./.github/workflows/deploy_api.yml
    secrets: inherit
    needs: [changes, test]
    if: needs.changes.outputs.run-deploy == 'true'

  deploy-prefect:
    uses: ./.github/workflows/prefect_deploy.yml
    needs: [changes, test]
    if: ${{ needs.changes.outputs.run-prefect-deploy == 'true' }}
    secrets: inherit

  vespa-deploy:
    uses: ./.github/workflows/vespa_deploy.yml
    secrets: inherit
    needs: [changes, test]
    if: needs.changes.outputs.run-vespa-deploy == 'true'

  vespa-feeder-deploy:
    uses: ./.github/workflows/vespa_feeder_deploy.yml
    secrets: inherit
    needs: [changes, test]
    if: needs.changes.outputs.run-vespa-feeder-deploy == 'true'

  pulumi-up:
    uses: ./.github/workflows/pulumi_up.yml
    secrets: inherit
    needs: [changes]
    if: needs.changes.outputs.run-pulumi-up == 'true'
    with:
      environment: production
